[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "io"
version = "0.1.0"
description = "I/O utilities and helper modules for the ICDAR typography project."
authors = [
    { name = "Diego" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "PyMuPDF==1.25.1",
    "torchvision",
    "ninja",
    "yacs",
    "cython",
    "matplotlib",
    "tqdm",
    "opencv-python",
    "scikit-image"
]

[tool.setuptools.packages.find]
where = ["src"]
