[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sueltas-typ"
version = "0.1.0"
description = "Full pipeline for the sueltas typography analysis article: PDF extraction, OCR (CharNet), and typographic feature computation."
authors = [
    { name = "Diego Belzarena" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "PyMuPDF==1.25.1",
    "torchvision",
    "ninja",
    "yacs",
    "cython",
    "matplotlib",
    "tqdm",
    "opencv-python",
    "scikit-image",
    "editdistance",
    "pyclipper",
    "shapely",
    "joblib",
    "scikit-learn",
    "pandas"
]

[tool.setuptools.packages.find]
where = ["src", "src/charnet_src"]
